//
// Created by mike on 06/08/2026.
//

#ifndef AERON_AERON_ARCHIVE_CLIENT_ERROR_H
#define AERON_AERON_ARCHIVE_CLIENT_ERROR_H

#define AERON_ARCHIVE_ERROR_CODE_GENERIC (200)
#define AERON_ARCHIVE_ERROR_CODE_ACTIVE_LISTING (201)
#define AERON_ARCHIVE_ERROR_CODE_ACTIVE_RECORDING (202)
#define AERON_ARCHIVE_ERROR_CODE_ACTIVE_SUBSCRIPTION (203)
#define AERON_ARCHIVE_ERROR_CODE_UNKNOWN_SUBSCRIPTION (204)
#define AERON_ARCHIVE_ERROR_CODE_UNKNOWN_RECORDING (205)
#define AERON_ARCHIVE_ERROR_CODE_UNKNOWN_REPLAY (206)
#define AERON_ARCHIVE_ERROR_CODE_MAX_REPLAYS (207)
#define AERON_ARCHIVE_ERROR_CODE_MAX_RECORDINGS (208)
#define AERON_ARCHIVE_ERROR_CODE_INVALID_EXTENSION (209)
#define AERON_ARCHIVE_ERROR_CODE_AUTHENTICATION_REJECTED (210)
#define AERON_ARCHIVE_ERROR_CODE_STORAGE_SPACE (211)
#define AERON_ARCHIVE_ERROR_CODE_UNKNOWN_REPLICATION (212)
#define AERON_ARCHIVE_ERROR_CODE_UNAUTHORISED_ACTION (213)
#define AERON_ARCHIVE_ERROR_CODE_REPLICATION_CONNECTION_FAILURE (214)
#define AERON_ARCHIVE_ERROR_CODE_EMPTY_RECORDING (215)
#define AERON_ARCHIVE_ERROR_CODE_INVALID_POSITION (216)

#endif //AERON_AERON_ARCHIVE_CLIENT_ERROR_H
