//
// Created by mike on 06/08/2026.
//

#ifndef AERON_AERON_CLIENT_ERROR_H
#define AERON_AERON_CLIENT_ERROR_H

/* error codes */
#define AERON_ERROR_CODE_UNKNOWN_CODE_VALUE (-1)
#define AERON_ERROR_CODE_UNUSED (0)
#define AERON_ERROR_CODE_INVALID_CHANNEL (1)
#define AERON_ERROR_CODE_UNKNOWN_SUBSCRIPTION (2)
#define AERON_ERROR_CODE_UNKNOWN_PUBLICATION (3)
#define AERON_ERROR_CODE_CHANNEL_ENDPOINT_ERROR (4)
#define AERON_ERROR_CODE_UNKNOWN_COUNTER (5)
#define AERON_ERROR_CODE_UNKNOWN_COMMAND_TYPE_ID (6)
#define AERON_ERROR_CODE_MALFORMED_COMMAND (7)
#define AERON_ERROR_CODE_NOT_SUPPORTED (8)
#define AERON_ERROR_CODE_UNKNOWN_HOST (9)
#define AERON_ERROR_CODE_RESOURCE_TEMPORARILY_UNAVAILABLE (10)
#define AERON_ERROR_CODE_GENERIC_ERROR (11)
#define AERON_ERROR_CODE_STORAGE_SPACE (12)
#define AERON_ERROR_CODE_IMAGE_REJECTED (13)
#define AERON_ERROR_CODE_PUBLICATION_REVOKED (14)

#endif //AERON_AERON_CLIENT_ERROR_H
