name: Continuous Integration

on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: run-commit-tests
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - 'release/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'
  INSTALL_COMPILER_RETRIES: '5'
  JAVA_VERSION: '17'

permissions:
  contents: read

jobs:
  java-build:
    name: Java ${{ matrix.java }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21', '25' ]
        os: ['ubuntu-24.04', 'windows-latest', 'macos-15']
    steps:
      - name: Print workspace and other dirs
        if: runner.os == 'Windows'
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "env.GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          echo "github.workspace: ${{ github.workspace }}"
          echo "env.TMP: $env:TMP"
          echo "env.TEMP: $env:TEMP"
          echo "JAVA_HOME: $env:JAVA_HOME"
          echo "MAVEN_HOME: $env:MAVEN_HOME"
          echo "M2_HOME: $env:M2_HOME"
          echo "GRADLE_HOME: $env:GRADLE_HOME"
          echo "PATH: $env:PATH"
          echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "env.RUNNER_TOOL_CACHE: $env:RUNNER_TOOL_CACHE"
          echo "env.RUNNER_TEMP: $env:RUNNER_TEMP"
          Get-WmiObject -Class Win32_LogicalDisk | ? {$_. DriveType -eq 3} | select DeviceID, {$_.Size /1GB}, {$_.FreeSpace /1GB}
          $new_workspace = "D:/custom_workspace"
          New-Item -Type Directory -Path $new_workspace
          echo "GITHUB_WORKSPACE=$new_workspace" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
          echo "(after) env.GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION (Unix)
        if: runner.os != 'Windows'
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=${{ matrix.java }}" >> $GITHUB_ENV
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION (Windows)
        if: runner.os == 'Windows'
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=$env:JAVA_HOME" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
          echo "BUILD_JAVA_VERSION=${{ matrix.java }}" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Setup java to run Gradle
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup small temp file system (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo mkdir -p /mnt/tmp_aeron_dir
          sudo mount -t tmpfs -o size=50M,mode=777 tmpfs /mnt/tmp_aeron_dir
      - name: Setup small temp file system and localhost name (MacOS)
        if: runner.os == 'macOS'
        run: |
          sudo sed -i bak "s/localhost/localhost $(hostname)/" /etc/hosts
          dscacheutil -flushcache
          sudo diskutil eraseDisk APFS tmp_aeron_dir $(hdiutil attach -nomount ram://$((2 * 1024 * 60)))
      - name: Setup small temp file system (Windows)
        if: runner.os == 'Windows'
        run: |
          $current_size = (Get-PartitionSupportedSize -DiskNumber 1 -PartitionNumber 1)
          $new_size = ($current_size.SizeMax - 100 * 1024 * 1024)
          Resize-Partition -DiskNumber 1 -PartitionNumber 1 -Size ($new_size)
          New-Partition -DiskNumber 1 -Size 60MB -DriveLetter T | Format-Volume -FileSystem NTFS -Confirm:$false
          mkdir T:/tmp_aeron_dir
      - name: Enable core dumps (Linux)
        if: runner.os == 'Linux'
        run: |
          ulimit -c unlimited
          sudo systemctl stop apport.service || true
          sudo systemctl disable apport.service || true
          sudo mkdir -p /var/coredump
          sudo chmod a+rw /var/coredump
          sudo sysctl -w kernel.core_pattern="/var/coredump/core_%e.%p"
      - name: Enable core dumps (MacOS)
        if: runner.os == 'macOS'
        run: |
          ulimit -c unlimited
          sudo mkdir -p /var/coredump
          sudo chmod a+rw /var/coredump
          sudo sysctl -w kern.coredump=1
          sudo sysctl -w kern.corefile="/var/coredump/core.%P"
      - name: Build with Gradle
        run: ./gradlew -x javadoc --console=plain
      - name: Remove small temp file system (Linux)
        if: always() && runner.os == 'Linux'
        run: |
          sudo umount /mnt/tmp_aeron_dir
          sudo rm -rf /mnt/tmp_aeron_dir
      - name: Remove small temp file system (MacOS)
        if: always() && runner.os == 'macOS'
        run: sudo diskutil eject tmp_aeron_dir
      - name: Remove small temp file system (Windows)
        if: always() && runner.os == 'Windows'
        run: Remove-Partition -DriveLetter T -Confirm:$false
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          ${{ runner.os == 'Windows' && 'echo "file=build/distributions/test_logs.tbz2" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append' || 'echo "file=build/distributions/test_logs.tbz2" >> $GITHUB_OUTPUT' }}
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-${{ matrix.os }}-java-${{ matrix.java }}
          path: ${{ steps.copy_test_logs.outputs.file }}

  java-topology-build:
    name: Java Topology Tests (JDK ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        os: [ 'ubuntu-24.04' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=${{ matrix.java }}" >> $GITHUB_ENV
      - name: Setup virtual network interfaces
        run: ./aeron-samples/scripts/cluster/setup-namespaces
      - name: Build aeron with Gradle
        run: ./gradlew clean assemble -x javadoc
      - name: Run execution agents
        working-directory: ./aeron-samples/scripts/cluster
        run: ./agent-ns
      - name: Get network information
        run:  |
          sudo sysctl -w net.ipv4.ip_forward=1
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
      - name: Run topology tests with Gradle
        run: ./gradlew topologyTest
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          ${{ runner.os == 'Windows' && 'echo "file=build/distributions/test_logs.tbz2" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append' || 'echo "file=build/distributions/test_logs.tbz2" >> $GITHUB_OUTPUT' }}
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-topology-${{ matrix.os }}-java-${{ matrix.java }}
          path: ${{ steps.copy_test_logs.outputs.file }}

  cpp-gcc-2404-build:
    name: C++ GCC ${{ matrix.version }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version: [ '11', '12', '13', '14' ]
    env:
      CC: gcc-${{ matrix.version }}
      CXX: g++-${{ matrix.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=${{ env.JAVA_VERSION }}" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install compiler
        run: |
          echo 'Acquire::Retries "${INSTALL_COMPILER_RETRIES}";' | sudo tee -a /etc/apt/apt.conf.d/99retries
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-${{ matrix.version }} libbsd-dev uuid-dev
      - name: Setup small temp file system
        run: |
          sudo mkdir -p /mnt/tmp_aeron_dir
          sudo mount -t tmpfs -o size=50M,mode=777 tmpfs /mnt/tmp_aeron_dir
      - name: Build
        run: cppbuild/cppbuild --c-warnings-as-errors --cxx-warnings-as-errors --cxx-hide-deprecation-message
      - name: Remove small temp file system
        if: always()
        run: |
          sudo umount /mnt/tmp_aeron_dir
          sudo rm -rf /mnt/tmp_aeron_dir
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          echo "file=build/distributions/test_logs.tbz2" >> $GITHUB_OUTPUT
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-gcc-2404-${{ matrix.version }}
          path: ${{ steps.copy_test_logs.outputs.file }}

  cpp-gcc-rocky-build:
    name: C++ Rocky 9
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version: [ '13' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: GCC_VERSION=${{ matrix.version }} cppbuild/rocky-docker-build
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          echo "file=build/distributions/test_logs.tbz2" >> $GITHUB_OUTPUT
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-gcc-rhel-${{ matrix.version }}
          path: ${{ steps.copy_test_logs.outputs.file }}

  cpp-clang-ubuntu-2404-build:
    name: C++ Clang ${{ matrix.version }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version: [ '17', '18', '19', '20', '21' ]
    env:
      CC: clang-${{ matrix.version }}
      CXX: clang++-${{ matrix.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=${{ env.JAVA_VERSION }}" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install compiler
        run: |
          echo 'Acquire::Retries "${INSTALL_COMPILER_RETRIES}";' | sudo tee -a /etc/apt/apt.conf.d/99retries
          sudo mkdir -p /etc/apt/keyrings/
          curl --retry ${INSTALL_COMPILER_RETRIES} https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg
          echo "deb [signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] https://apt.llvm.org/noble/ llvm-toolchain-noble-${{ matrix.version }} main" | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt-get update
          sudo apt-get install -y clang-${{ matrix.version }} libbsd-dev uuid-dev
      - name: Setup small temp file system
        run: |
          sudo mkdir -p /mnt/tmp_aeron_dir
          sudo mount -t tmpfs -o size=50M,mode=777 tmpfs /mnt/tmp_aeron_dir
      - name: Build
        run: cppbuild/cppbuild --c-warnings-as-errors --cxx-warnings-as-errors --cxx-hide-deprecation-message
      - name: Remove small temp file system
        if: always()
        run: |
          sudo umount /mnt/tmp_aeron_dir
          sudo rm -rf /mnt/tmp_aeron_dir
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          echo "file=build/distributions/test_logs.tbz2" >> $GITHUB_OUTPUT
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-clang-2404-${{ matrix.version }}
          path: ${{ steps.copy_test_logs.outputs.file }}

  cpp-clang-debug-build:
    name: C++ Clang ${{ matrix.version }} debug build
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version: [ '21' ]
    env:
      CC: clang-${{ matrix.version }}
      CXX: clang++-${{ matrix.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=${{ env.JAVA_VERSION }}" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Install compiler
        run: |
          echo 'Acquire::Retries "${INSTALL_COMPILER_RETRIES}";' | sudo tee -a /etc/apt/apt.conf.d/99retries
          sudo mkdir -p /etc/apt/keyrings/
          curl --retry ${INSTALL_COMPILER_RETRIES} https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg
          echo "deb [signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] https://apt.llvm.org/noble/ llvm-toolchain-noble-${{ matrix.version }} main" | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt-get update
          sudo apt-get install -y clang-${{ matrix.version }} libbsd-dev uuid-dev
      - name: Build
        run: cppbuild/cppbuild --debug-build --cxx-hide-deprecation-message
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          echo "file=build/distributions/test_logs.tbz2" >> $GITHUB_OUTPUT
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-clang-debug-${{ matrix.version }}
          path: ${{ steps.copy_test_logs.outputs.file }}

  cpp-xcode-build:
    name: C++ Xcode (macOS)
    runs-on: macos-15
    timeout-minutes: 60
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=${{ env.JAVA_VERSION }}" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup small temp file system and localhost name
        run: |
          sudo sed -i bak "s/localhost/localhost $(hostname)/" /etc/hosts
          dscacheutil -flushcache
          sudo diskutil eraseDisk APFS tmp_aeron_dir $(hdiutil attach -nomount ram://$((2 * 1024 * 60)))
      - name: Build
        run: cppbuild/cppbuild --c-warnings-as-errors --cxx-warnings-as-errors --cxx-hide-deprecation-message
      - name: Remove small temp file system
        run: sudo diskutil eject tmp_aeron_dir
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          echo "file=build/distributions/test_logs.tbz2" >> $GITHUB_OUTPUT
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-xcode-latest
          path: ${{ steps.copy_test_logs.outputs.file }}

  cpp-msvc-build:
    name: C++ MSVC (Windows)
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      CC: cl
      CXX: cl
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=$env:JAVA_HOME" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
          echo "BUILD_JAVA_VERSION=${{ env.JAVA_VERSION }}" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup small temp file system
        run: |
          $current_size = (Get-PartitionSupportedSize -DiskNumber 1 -PartitionNumber 1)
          $new_size = ($current_size.SizeMax - 100 * 1024 * 1024)
          Resize-Partition -DiskNumber 1 -PartitionNumber 1 -Size ($new_size)
          New-Partition -DiskNumber 1 -Size 60MB -DriveLetter T | Format-Volume -FileSystem NTFS -Confirm:$false
          mkdir T:/tmp_aeron_dir
      - name: Build
        run: cppbuild/cppbuild.ps1 --cxx-hide-deprecation-message
      - name: Remove small temp file system
        run: Remove-Partition -DriveLetter T -Confirm:$false
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          echo "file=build/distributions/test_logs.tbz2" | Out-File $env:GITHUB_OUTPUT -Encoding utf8 -Append
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-msvc-latest
          path: ${{ steps.copy_test_logs.outputs.file }}
